# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: event_bus.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'event_bus.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65vent_bus.proto\x12\x02\x65\x62\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\x1a\n\x07Message\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\"L\n\x0ePublishRequest\x12\x1c\n\x05\x65vent\x18\x01 \x01(\x0e\x32\r.eb.EventType\x12\x1c\n\x07message\x18\x02 \x01(\x0b\x32\x0b.eb.Message\"0\n\x10SubscribeRequest\x12\x1c\n\x05\x65vent\x18\x01 \x01(\x0e\x32\r.eb.EventType\",\n\x1bNumberOfSubscribersResponse\x12\r\n\x05\x63ount\x18\x01 \x01(\x05*2\n\tEventType\x12\x0b\n\x07\x45VENT_A\x10\x00\x12\x0b\n\x07\x45VENT_B\x10\x01\x12\x0b\n\x07\x45VENT_C\x10\x02\x32\xc6\x01\n\x08\x45ventBus\x12\x35\n\x07Publish\x12\x12.eb.PublishRequest\x1a\x16.google.protobuf.Empty\x12\x30\n\tSubscribe\x12\x14.eb.SubscribeRequest\x1a\x0b.eb.Message0\x01\x12Q\n\x16getNumberOfSubscribers\x12\x16.google.protobuf.Empty\x1a\x1f.eb.NumberOfSubscribersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'event_bus_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENTTYPE']._serialized_start=286
  _globals['_EVENTTYPE']._serialized_end=336
  _globals['_MESSAGE']._serialized_start=84
  _globals['_MESSAGE']._serialized_end=110
  _globals['_PUBLISHREQUEST']._serialized_start=112
  _globals['_PUBLISHREQUEST']._serialized_end=188
  _globals['_SUBSCRIBEREQUEST']._serialized_start=190
  _globals['_SUBSCRIBEREQUEST']._serialized_end=238
  _globals['_NUMBEROFSUBSCRIBERSRESPONSE']._serialized_start=240
  _globals['_NUMBEROFSUBSCRIBERSRESPONSE']._serialized_end=284
  _globals['_EVENTBUS']._serialized_start=339
  _globals['_EVENTBUS']._serialized_end=537
# @@protoc_insertion_point(module_scope)
